[default]

[default.stackspot]
agent_id = "01K950EYCETA9KX9XBMNNAHE49"

[default.stackspot.auth]
base_url = "https://idm.stackspot.com"
api_version = "v1"
oidc_resource = "oidc"
oauth_resource = "oauth"
token_resource = "token" 

[default.stackspot.inference]
base_url = "https://genai-inference-app.stackspot.com"
api_version = "v1"
agent_resource = "agent"
chat_endpoint = "chat"

[development]
debug = true
log_level = "DEBUG"

[production]
debug = false
log_level = "INFO"
